version: '2'

networks:
    database:
        driver: bridge
    redis:
        driver: bridge

services:
    agent:
        build:
            context: .
            dockerfile: Dockerfile
        environment:
            NEWRELIC_KEY: ""

            NPOSTGRES_HOST_DB1: 172.18.0.1
            NPOSTGRES_NAME_DB1: TEST-DB-1
            NPOSTGRES_PORT_DB1: 5432
            NPOSTGRES_USER_DB1: db_user
            NPOSTGRES_PASS_DB1: db_pass
            NPOSTGRES_DBNAME_DB1: db_db

            NREDIS_HOST_RD: 172.18.0.1
            NREDIS_NAME_RD: TEST-REDIS-1
            NREDIS_PORT_RD: 6379

            NRABBITMQ_HOST_NODE1: 172.18.0.1
            NRABBITMQ_NAME_NODE1: RMQ-1
        volumes_from:
            - sources:rw
        depends_on:
            - redis
            - postgres

    redis:
        image: relaxart/kubernetes-redis-cluster
        environment:
          MASTER: "1"
        ports:
          - "6379:6379"
        networks:
            redis:
                aliases:
                    - redis

    rabbitmq:
        image: rabbitmq
        ports:
          - "15672:15672"

    postgres:
        image: postgres:9.5
        environment:
            POSTGRES_PASSWORD: db_pass
            POSTGRES_USER: db_user
            POSTGRES_DB: db_db
        ports:
            - 5432:5432
        networks:
            database:
                aliases:
                    - database

    sources:
        image: ubuntu
        volumes:
            - ./docker/newrelic_agent/:/usr/local/bin/agent/:rw